# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-${infra.kubernetes.release.name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      version: ${serviceVariable.version}  # Set by Harness
  template:
    metadata:
      labels:
        app: flask
        version: ${serviceVariable.version}
    spec:
      containers:
      - name: flask-app
        image: mdirshaq/flask-web-app:${serviceVariable.tag}
        ports:
        - containerPort: 5000
