apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: blue  # This should match the label in the Deployment
  ports:
    - port: 5000
      targetPort: 5000
